<Project>
  <ItemGroup>
    <PackageVersion Include="MailKit" Version="4.17.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="10.0.80" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.80" />
    <PackageVersion Include="Microsoft.OpenApi" Version="3.8.0" />
    <PackageVersion Include="MimeKit" Version="4.17.0" />
    <PackageVersion Include="NLog" Version="6.1.4" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.16.11" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>
</Project>