<Project Sdk="Microsoft.NET.Sdk.Razor">


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Promise.Common\Promise.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Components/Pages/Profile.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components/Pages/Profile.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Components\Pages\RestoreAccess\RestoreAccessUseTel.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\Pages\RestoreAccess\RestoreAccessUseEmail.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>


</Project>

